/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuspendedRouteImport } from './routes/suspended'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as AppCompanyIdRouteImport } from './routes/app.$companyId'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCompaniesRouteImport } from './routes/admin.companies'
import { Route as AppCompanyIdIndexRouteImport } from './routes/app.$companyId.index'
import { Route as AppCompanyIdWeaponsRouteImport } from './routes/app.$companyId.weapons'
import { Route as AppCompanyIdUsersRouteImport } from './routes/app.$companyId.users'
import { Route as AppCompanyIdUnitsRouteImport } from './routes/app.$companyId.units'
import { Route as AppCompanyIdScheduleRouteImport } from './routes/app.$companyId.schedule'
import { Route as AppCompanyIdRangeRouteImport } from './routes/app.$companyId.range'
import { Route as AppCompanyIdNotificationsRouteImport } from './routes/app.$companyId.notifications'
import { Route as AppCompanyIdLojaRouteImport } from './routes/app.$companyId.loja'
import { Route as AppCompanyIdFinanceRouteImport } from './routes/app.$companyId.finance'
import { Route as AppCompanyIdDocumentsRouteImport } from './routes/app.$companyId.documents'
import { Route as AppCompanyIdClientsRouteImport } from './routes/app.$companyId.clients'
import { Route as AppCompanyIdBillingRouteImport } from './routes/app.$companyId.billing'
import { Route as AppCompanyIdAmmoRouteImport } from './routes/app.$companyId.ammo'
import { Route as AppCompanyIdLojaIndexRouteImport } from './routes/app.$companyId.loja.index'
import { Route as AppCompanyIdLojaVendasRouteImport } from './routes/app.$companyId.loja.vendas'
import { Route as AppCompanyIdLojaRelatoriosRouteImport } from './routes/app.$companyId.loja.relatorios'
import { Route as AppCompanyIdLojaProdutosRouteImport } from './routes/app.$companyId.loja.produtos'
import { Route as AppCompanyIdLojaFornecedoresRouteImport } from './routes/app.$companyId.loja.fornecedores'
import { Route as AppCompanyIdLojaFinanceiroRouteImport } from './routes/app.$companyId.loja.financeiro'
import { Route as AppCompanyIdLojaEstoqueRouteImport } from './routes/app.$companyId.loja.estoque'
import { Route as AppCompanyIdLojaDocumentosRouteImport } from './routes/app.$companyId.loja.documentos'
import { Route as AppCompanyIdLojaConfigRouteImport } from './routes/app.$companyId.loja.config'
import { Route as AppCompanyIdLojaComprasRouteImport } from './routes/app.$companyId.loja.compras'
import { Route as AppCompanyIdLojaClientesRouteImport } from './routes/app.$companyId.loja.clientes'
import { Route as AppCompanyIdLojaCategoriasRouteImport } from './routes/app.$companyId.loja.categorias'
import { Route as AppCompanyIdLojaAuditoriaRouteImport } from './routes/app.$companyId.loja.auditoria'

const SuspendedRoute = SuspendedRouteImport.update({
  id: '/suspended',
  path: '/suspended',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const AppCompanyIdRoute = AppCompanyIdRouteImport.update({
  id: '/app/$companyId',
  path: '/app/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AppCompanyIdIndexRoute = AppCompanyIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdWeaponsRoute = AppCompanyIdWeaponsRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdUsersRoute = AppCompanyIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdUnitsRoute = AppCompanyIdUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdScheduleRoute = AppCompanyIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdRangeRoute = AppCompanyIdRangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdNotificationsRoute =
  AppCompanyIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppCompanyIdRoute,
  } as any)
const AppCompanyIdLojaRoute = AppCompanyIdLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdFinanceRoute = AppCompanyIdFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdDocumentsRoute = AppCompanyIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdClientsRoute = AppCompanyIdClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdBillingRoute = AppCompanyIdBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdAmmoRoute = AppCompanyIdAmmoRouteImport.update({
  id: '/ammo',
  path: '/ammo',
  getParentRoute: () => AppCompanyIdRoute,
} as any)
const AppCompanyIdLojaIndexRoute = AppCompanyIdLojaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanyIdLojaRoute,
} as any)
const AppCompanyIdLojaVendasRoute = AppCompanyIdLojaVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AppCompanyIdLojaRoute,
} as any)
const AppCompanyIdLojaRelatoriosRoute =
  AppCompanyIdLojaRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaProdutosRoute =
  AppCompanyIdLojaProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaFornecedoresRoute =
  AppCompanyIdLojaFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaFinanceiroRoute =
  AppCompanyIdLojaFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaEstoqueRoute = AppCompanyIdLojaEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppCompanyIdLojaRoute,
} as any)
const AppCompanyIdLojaDocumentosRoute =
  AppCompanyIdLojaDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaConfigRoute = AppCompanyIdLojaConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppCompanyIdLojaRoute,
} as any)
const AppCompanyIdLojaComprasRoute = AppCompanyIdLojaComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppCompanyIdLojaRoute,
} as any)
const AppCompanyIdLojaClientesRoute =
  AppCompanyIdLojaClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaCategoriasRoute =
  AppCompanyIdLojaCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)
const AppCompanyIdLojaAuditoriaRoute =
  AppCompanyIdLojaAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AppCompanyIdLojaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/suspended': typeof SuspendedRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/app/$companyId': typeof AppCompanyIdRouteWithChildren
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/$companyId/ammo': typeof AppCompanyIdAmmoRoute
  '/app/$companyId/billing': typeof AppCompanyIdBillingRoute
  '/app/$companyId/clients': typeof AppCompanyIdClientsRoute
  '/app/$companyId/documents': typeof AppCompanyIdDocumentsRoute
  '/app/$companyId/finance': typeof AppCompanyIdFinanceRoute
  '/app/$companyId/loja': typeof AppCompanyIdLojaRouteWithChildren
  '/app/$companyId/notifications': typeof AppCompanyIdNotificationsRoute
  '/app/$companyId/range': typeof AppCompanyIdRangeRoute
  '/app/$companyId/schedule': typeof AppCompanyIdScheduleRoute
  '/app/$companyId/units': typeof AppCompanyIdUnitsRoute
  '/app/$companyId/users': typeof AppCompanyIdUsersRoute
  '/app/$companyId/weapons': typeof AppCompanyIdWeaponsRoute
  '/app/$companyId/': typeof AppCompanyIdIndexRoute
  '/app/$companyId/loja/auditoria': typeof AppCompanyIdLojaAuditoriaRoute
  '/app/$companyId/loja/categorias': typeof AppCompanyIdLojaCategoriasRoute
  '/app/$companyId/loja/clientes': typeof AppCompanyIdLojaClientesRoute
  '/app/$companyId/loja/compras': typeof AppCompanyIdLojaComprasRoute
  '/app/$companyId/loja/config': typeof AppCompanyIdLojaConfigRoute
  '/app/$companyId/loja/documentos': typeof AppCompanyIdLojaDocumentosRoute
  '/app/$companyId/loja/estoque': typeof AppCompanyIdLojaEstoqueRoute
  '/app/$companyId/loja/financeiro': typeof AppCompanyIdLojaFinanceiroRoute
  '/app/$companyId/loja/fornecedores': typeof AppCompanyIdLojaFornecedoresRoute
  '/app/$companyId/loja/produtos': typeof AppCompanyIdLojaProdutosRoute
  '/app/$companyId/loja/relatorios': typeof AppCompanyIdLojaRelatoriosRoute
  '/app/$companyId/loja/vendas': typeof AppCompanyIdLojaVendasRoute
  '/app/$companyId/loja/': typeof AppCompanyIdLojaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/suspended': typeof SuspendedRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/$companyId/ammo': typeof AppCompanyIdAmmoRoute
  '/app/$companyId/billing': typeof AppCompanyIdBillingRoute
  '/app/$companyId/clients': typeof AppCompanyIdClientsRoute
  '/app/$companyId/documents': typeof AppCompanyIdDocumentsRoute
  '/app/$companyId/finance': typeof AppCompanyIdFinanceRoute
  '/app/$companyId/notifications': typeof AppCompanyIdNotificationsRoute
  '/app/$companyId/range': typeof AppCompanyIdRangeRoute
  '/app/$companyId/schedule': typeof AppCompanyIdScheduleRoute
  '/app/$companyId/units': typeof AppCompanyIdUnitsRoute
  '/app/$companyId/users': typeof AppCompanyIdUsersRoute
  '/app/$companyId/weapons': typeof AppCompanyIdWeaponsRoute
  '/app/$companyId': typeof AppCompanyIdIndexRoute
  '/app/$companyId/loja/auditoria': typeof AppCompanyIdLojaAuditoriaRoute
  '/app/$companyId/loja/categorias': typeof AppCompanyIdLojaCategoriasRoute
  '/app/$companyId/loja/clientes': typeof AppCompanyIdLojaClientesRoute
  '/app/$companyId/loja/compras': typeof AppCompanyIdLojaComprasRoute
  '/app/$companyId/loja/config': typeof AppCompanyIdLojaConfigRoute
  '/app/$companyId/loja/documentos': typeof AppCompanyIdLojaDocumentosRoute
  '/app/$companyId/loja/estoque': typeof AppCompanyIdLojaEstoqueRoute
  '/app/$companyId/loja/financeiro': typeof AppCompanyIdLojaFinanceiroRoute
  '/app/$companyId/loja/fornecedores': typeof AppCompanyIdLojaFornecedoresRoute
  '/app/$companyId/loja/produtos': typeof AppCompanyIdLojaProdutosRoute
  '/app/$companyId/loja/relatorios': typeof AppCompanyIdLojaRelatoriosRoute
  '/app/$companyId/loja/vendas': typeof AppCompanyIdLojaVendasRoute
  '/app/$companyId/loja': typeof AppCompanyIdLojaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/suspended': typeof SuspendedRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/plans': typeof AdminPlansRoute
  '/app/$companyId': typeof AppCompanyIdRouteWithChildren
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/login': typeof PortalLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/$companyId/ammo': typeof AppCompanyIdAmmoRoute
  '/app/$companyId/billing': typeof AppCompanyIdBillingRoute
  '/app/$companyId/clients': typeof AppCompanyIdClientsRoute
  '/app/$companyId/documents': typeof AppCompanyIdDocumentsRoute
  '/app/$companyId/finance': typeof AppCompanyIdFinanceRoute
  '/app/$companyId/loja': typeof AppCompanyIdLojaRouteWithChildren
  '/app/$companyId/notifications': typeof AppCompanyIdNotificationsRoute
  '/app/$companyId/range': typeof AppCompanyIdRangeRoute
  '/app/$companyId/schedule': typeof AppCompanyIdScheduleRoute
  '/app/$companyId/units': typeof AppCompanyIdUnitsRoute
  '/app/$companyId/users': typeof AppCompanyIdUsersRoute
  '/app/$companyId/weapons': typeof AppCompanyIdWeaponsRoute
  '/app/$companyId/': typeof AppCompanyIdIndexRoute
  '/app/$companyId/loja/auditoria': typeof AppCompanyIdLojaAuditoriaRoute
  '/app/$companyId/loja/categorias': typeof AppCompanyIdLojaCategoriasRoute
  '/app/$companyId/loja/clientes': typeof AppCompanyIdLojaClientesRoute
  '/app/$companyId/loja/compras': typeof AppCompanyIdLojaComprasRoute
  '/app/$companyId/loja/config': typeof AppCompanyIdLojaConfigRoute
  '/app/$companyId/loja/documentos': typeof AppCompanyIdLojaDocumentosRoute
  '/app/$companyId/loja/estoque': typeof AppCompanyIdLojaEstoqueRoute
  '/app/$companyId/loja/financeiro': typeof AppCompanyIdLojaFinanceiroRoute
  '/app/$companyId/loja/fornecedores': typeof AppCompanyIdLojaFornecedoresRoute
  '/app/$companyId/loja/produtos': typeof AppCompanyIdLojaProdutosRoute
  '/app/$companyId/loja/relatorios': typeof AppCompanyIdLojaRelatoriosRoute
  '/app/$companyId/loja/vendas': typeof AppCompanyIdLojaVendasRoute
  '/app/$companyId/loja/': typeof AppCompanyIdLojaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/invite'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/reset-password'
    | '/suspended'
    | '/admin/companies'
    | '/admin/finance'
    | '/admin/plans'
    | '/app/$companyId'
    | '/portal/dashboard'
    | '/portal/login'
    | '/admin/'
    | '/portal/'
    | '/app/$companyId/ammo'
    | '/app/$companyId/billing'
    | '/app/$companyId/clients'
    | '/app/$companyId/documents'
    | '/app/$companyId/finance'
    | '/app/$companyId/loja'
    | '/app/$companyId/notifications'
    | '/app/$companyId/range'
    | '/app/$companyId/schedule'
    | '/app/$companyId/units'
    | '/app/$companyId/users'
    | '/app/$companyId/weapons'
    | '/app/$companyId/'
    | '/app/$companyId/loja/auditoria'
    | '/app/$companyId/loja/categorias'
    | '/app/$companyId/loja/clientes'
    | '/app/$companyId/loja/compras'
    | '/app/$companyId/loja/config'
    | '/app/$companyId/loja/documentos'
    | '/app/$companyId/loja/estoque'
    | '/app/$companyId/loja/financeiro'
    | '/app/$companyId/loja/fornecedores'
    | '/app/$companyId/loja/produtos'
    | '/app/$companyId/loja/relatorios'
    | '/app/$companyId/loja/vendas'
    | '/app/$companyId/loja/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/suspended'
    | '/admin/companies'
    | '/admin/finance'
    | '/admin/plans'
    | '/portal/dashboard'
    | '/portal/login'
    | '/admin'
    | '/portal'
    | '/app/$companyId/ammo'
    | '/app/$companyId/billing'
    | '/app/$companyId/clients'
    | '/app/$companyId/documents'
    | '/app/$companyId/finance'
    | '/app/$companyId/notifications'
    | '/app/$companyId/range'
    | '/app/$companyId/schedule'
    | '/app/$companyId/units'
    | '/app/$companyId/users'
    | '/app/$companyId/weapons'
    | '/app/$companyId'
    | '/app/$companyId/loja/auditoria'
    | '/app/$companyId/loja/categorias'
    | '/app/$companyId/loja/clientes'
    | '/app/$companyId/loja/compras'
    | '/app/$companyId/loja/config'
    | '/app/$companyId/loja/documentos'
    | '/app/$companyId/loja/estoque'
    | '/app/$companyId/loja/financeiro'
    | '/app/$companyId/loja/fornecedores'
    | '/app/$companyId/loja/produtos'
    | '/app/$companyId/loja/relatorios'
    | '/app/$companyId/loja/vendas'
    | '/app/$companyId/loja'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/invite'
    | '/login'
    | '/onboarding'
    | '/portal'
    | '/reset-password'
    | '/suspended'
    | '/admin/companies'
    | '/admin/finance'
    | '/admin/plans'
    | '/app/$companyId'
    | '/portal/dashboard'
    | '/portal/login'
    | '/admin/'
    | '/portal/'
    | '/app/$companyId/ammo'
    | '/app/$companyId/billing'
    | '/app/$companyId/clients'
    | '/app/$companyId/documents'
    | '/app/$companyId/finance'
    | '/app/$companyId/loja'
    | '/app/$companyId/notifications'
    | '/app/$companyId/range'
    | '/app/$companyId/schedule'
    | '/app/$companyId/units'
    | '/app/$companyId/users'
    | '/app/$companyId/weapons'
    | '/app/$companyId/'
    | '/app/$companyId/loja/auditoria'
    | '/app/$companyId/loja/categorias'
    | '/app/$companyId/loja/clientes'
    | '/app/$companyId/loja/compras'
    | '/app/$companyId/loja/config'
    | '/app/$companyId/loja/documentos'
    | '/app/$companyId/loja/estoque'
    | '/app/$companyId/loja/financeiro'
    | '/app/$companyId/loja/fornecedores'
    | '/app/$companyId/loja/produtos'
    | '/app/$companyId/loja/relatorios'
    | '/app/$companyId/loja/vendas'
    | '/app/$companyId/loja/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuspendedRoute: typeof SuspendedRoute
  AppCompanyIdRoute: typeof AppCompanyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suspended': {
      id: '/suspended'
      path: '/suspended'
      fullPath: '/suspended'
      preLoaderRoute: typeof SuspendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/$companyId': {
      id: '/app/$companyId'
      path: '/app/$companyId'
      fullPath: '/app/$companyId'
      preLoaderRoute: typeof AppCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/$companyId/': {
      id: '/app/$companyId/'
      path: '/'
      fullPath: '/app/$companyId/'
      preLoaderRoute: typeof AppCompanyIdIndexRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/weapons': {
      id: '/app/$companyId/weapons'
      path: '/weapons'
      fullPath: '/app/$companyId/weapons'
      preLoaderRoute: typeof AppCompanyIdWeaponsRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/users': {
      id: '/app/$companyId/users'
      path: '/users'
      fullPath: '/app/$companyId/users'
      preLoaderRoute: typeof AppCompanyIdUsersRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/units': {
      id: '/app/$companyId/units'
      path: '/units'
      fullPath: '/app/$companyId/units'
      preLoaderRoute: typeof AppCompanyIdUnitsRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/schedule': {
      id: '/app/$companyId/schedule'
      path: '/schedule'
      fullPath: '/app/$companyId/schedule'
      preLoaderRoute: typeof AppCompanyIdScheduleRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/range': {
      id: '/app/$companyId/range'
      path: '/range'
      fullPath: '/app/$companyId/range'
      preLoaderRoute: typeof AppCompanyIdRangeRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/notifications': {
      id: '/app/$companyId/notifications'
      path: '/notifications'
      fullPath: '/app/$companyId/notifications'
      preLoaderRoute: typeof AppCompanyIdNotificationsRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/loja': {
      id: '/app/$companyId/loja'
      path: '/loja'
      fullPath: '/app/$companyId/loja'
      preLoaderRoute: typeof AppCompanyIdLojaRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/finance': {
      id: '/app/$companyId/finance'
      path: '/finance'
      fullPath: '/app/$companyId/finance'
      preLoaderRoute: typeof AppCompanyIdFinanceRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/documents': {
      id: '/app/$companyId/documents'
      path: '/documents'
      fullPath: '/app/$companyId/documents'
      preLoaderRoute: typeof AppCompanyIdDocumentsRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/clients': {
      id: '/app/$companyId/clients'
      path: '/clients'
      fullPath: '/app/$companyId/clients'
      preLoaderRoute: typeof AppCompanyIdClientsRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/billing': {
      id: '/app/$companyId/billing'
      path: '/billing'
      fullPath: '/app/$companyId/billing'
      preLoaderRoute: typeof AppCompanyIdBillingRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/ammo': {
      id: '/app/$companyId/ammo'
      path: '/ammo'
      fullPath: '/app/$companyId/ammo'
      preLoaderRoute: typeof AppCompanyIdAmmoRouteImport
      parentRoute: typeof AppCompanyIdRoute
    }
    '/app/$companyId/loja/': {
      id: '/app/$companyId/loja/'
      path: '/'
      fullPath: '/app/$companyId/loja/'
      preLoaderRoute: typeof AppCompanyIdLojaIndexRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/vendas': {
      id: '/app/$companyId/loja/vendas'
      path: '/vendas'
      fullPath: '/app/$companyId/loja/vendas'
      preLoaderRoute: typeof AppCompanyIdLojaVendasRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/relatorios': {
      id: '/app/$companyId/loja/relatorios'
      path: '/relatorios'
      fullPath: '/app/$companyId/loja/relatorios'
      preLoaderRoute: typeof AppCompanyIdLojaRelatoriosRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/produtos': {
      id: '/app/$companyId/loja/produtos'
      path: '/produtos'
      fullPath: '/app/$companyId/loja/produtos'
      preLoaderRoute: typeof AppCompanyIdLojaProdutosRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/fornecedores': {
      id: '/app/$companyId/loja/fornecedores'
      path: '/fornecedores'
      fullPath: '/app/$companyId/loja/fornecedores'
      preLoaderRoute: typeof AppCompanyIdLojaFornecedoresRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/financeiro': {
      id: '/app/$companyId/loja/financeiro'
      path: '/financeiro'
      fullPath: '/app/$companyId/loja/financeiro'
      preLoaderRoute: typeof AppCompanyIdLojaFinanceiroRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/estoque': {
      id: '/app/$companyId/loja/estoque'
      path: '/estoque'
      fullPath: '/app/$companyId/loja/estoque'
      preLoaderRoute: typeof AppCompanyIdLojaEstoqueRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/documentos': {
      id: '/app/$companyId/loja/documentos'
      path: '/documentos'
      fullPath: '/app/$companyId/loja/documentos'
      preLoaderRoute: typeof AppCompanyIdLojaDocumentosRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/config': {
      id: '/app/$companyId/loja/config'
      path: '/config'
      fullPath: '/app/$companyId/loja/config'
      preLoaderRoute: typeof AppCompanyIdLojaConfigRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/compras': {
      id: '/app/$companyId/loja/compras'
      path: '/compras'
      fullPath: '/app/$companyId/loja/compras'
      preLoaderRoute: typeof AppCompanyIdLojaComprasRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/clientes': {
      id: '/app/$companyId/loja/clientes'
      path: '/clientes'
      fullPath: '/app/$companyId/loja/clientes'
      preLoaderRoute: typeof AppCompanyIdLojaClientesRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/categorias': {
      id: '/app/$companyId/loja/categorias'
      path: '/categorias'
      fullPath: '/app/$companyId/loja/categorias'
      preLoaderRoute: typeof AppCompanyIdLojaCategoriasRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
    '/app/$companyId/loja/auditoria': {
      id: '/app/$companyId/loja/auditoria'
      path: '/auditoria'
      fullPath: '/app/$companyId/loja/auditoria'
      preLoaderRoute: typeof AppCompanyIdLojaAuditoriaRouteImport
      parentRoute: typeof AppCompanyIdLojaRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface AppCompanyIdLojaRouteChildren {
  AppCompanyIdLojaAuditoriaRoute: typeof AppCompanyIdLojaAuditoriaRoute
  AppCompanyIdLojaCategoriasRoute: typeof AppCompanyIdLojaCategoriasRoute
  AppCompanyIdLojaClientesRoute: typeof AppCompanyIdLojaClientesRoute
  AppCompanyIdLojaComprasRoute: typeof AppCompanyIdLojaComprasRoute
  AppCompanyIdLojaConfigRoute: typeof AppCompanyIdLojaConfigRoute
  AppCompanyIdLojaDocumentosRoute: typeof AppCompanyIdLojaDocumentosRoute
  AppCompanyIdLojaEstoqueRoute: typeof AppCompanyIdLojaEstoqueRoute
  AppCompanyIdLojaFinanceiroRoute: typeof AppCompanyIdLojaFinanceiroRoute
  AppCompanyIdLojaFornecedoresRoute: typeof AppCompanyIdLojaFornecedoresRoute
  AppCompanyIdLojaProdutosRoute: typeof AppCompanyIdLojaProdutosRoute
  AppCompanyIdLojaRelatoriosRoute: typeof AppCompanyIdLojaRelatoriosRoute
  AppCompanyIdLojaVendasRoute: typeof AppCompanyIdLojaVendasRoute
  AppCompanyIdLojaIndexRoute: typeof AppCompanyIdLojaIndexRoute
}

const AppCompanyIdLojaRouteChildren: AppCompanyIdLojaRouteChildren = {
  AppCompanyIdLojaAuditoriaRoute: AppCompanyIdLojaAuditoriaRoute,
  AppCompanyIdLojaCategoriasRoute: AppCompanyIdLojaCategoriasRoute,
  AppCompanyIdLojaClientesRoute: AppCompanyIdLojaClientesRoute,
  AppCompanyIdLojaComprasRoute: AppCompanyIdLojaComprasRoute,
  AppCompanyIdLojaConfigRoute: AppCompanyIdLojaConfigRoute,
  AppCompanyIdLojaDocumentosRoute: AppCompanyIdLojaDocumentosRoute,
  AppCompanyIdLojaEstoqueRoute: AppCompanyIdLojaEstoqueRoute,
  AppCompanyIdLojaFinanceiroRoute: AppCompanyIdLojaFinanceiroRoute,
  AppCompanyIdLojaFornecedoresRoute: AppCompanyIdLojaFornecedoresRoute,
  AppCompanyIdLojaProdutosRoute: AppCompanyIdLojaProdutosRoute,
  AppCompanyIdLojaRelatoriosRoute: AppCompanyIdLojaRelatoriosRoute,
  AppCompanyIdLojaVendasRoute: AppCompanyIdLojaVendasRoute,
  AppCompanyIdLojaIndexRoute: AppCompanyIdLojaIndexRoute,
}

const AppCompanyIdLojaRouteWithChildren =
  AppCompanyIdLojaRoute._addFileChildren(AppCompanyIdLojaRouteChildren)

interface AppCompanyIdRouteChildren {
  AppCompanyIdAmmoRoute: typeof AppCompanyIdAmmoRoute
  AppCompanyIdBillingRoute: typeof AppCompanyIdBillingRoute
  AppCompanyIdClientsRoute: typeof AppCompanyIdClientsRoute
  AppCompanyIdDocumentsRoute: typeof AppCompanyIdDocumentsRoute
  AppCompanyIdFinanceRoute: typeof AppCompanyIdFinanceRoute
  AppCompanyIdLojaRoute: typeof AppCompanyIdLojaRouteWithChildren
  AppCompanyIdNotificationsRoute: typeof AppCompanyIdNotificationsRoute
  AppCompanyIdRangeRoute: typeof AppCompanyIdRangeRoute
  AppCompanyIdScheduleRoute: typeof AppCompanyIdScheduleRoute
  AppCompanyIdUnitsRoute: typeof AppCompanyIdUnitsRoute
  AppCompanyIdUsersRoute: typeof AppCompanyIdUsersRoute
  AppCompanyIdWeaponsRoute: typeof AppCompanyIdWeaponsRoute
  AppCompanyIdIndexRoute: typeof AppCompanyIdIndexRoute
}

const AppCompanyIdRouteChildren: AppCompanyIdRouteChildren = {
  AppCompanyIdAmmoRoute: AppCompanyIdAmmoRoute,
  AppCompanyIdBillingRoute: AppCompanyIdBillingRoute,
  AppCompanyIdClientsRoute: AppCompanyIdClientsRoute,
  AppCompanyIdDocumentsRoute: AppCompanyIdDocumentsRoute,
  AppCompanyIdFinanceRoute: AppCompanyIdFinanceRoute,
  AppCompanyIdLojaRoute: AppCompanyIdLojaRouteWithChildren,
  AppCompanyIdNotificationsRoute: AppCompanyIdNotificationsRoute,
  AppCompanyIdRangeRoute: AppCompanyIdRangeRoute,
  AppCompanyIdScheduleRoute: AppCompanyIdScheduleRoute,
  AppCompanyIdUnitsRoute: AppCompanyIdUnitsRoute,
  AppCompanyIdUsersRoute: AppCompanyIdUsersRoute,
  AppCompanyIdWeaponsRoute: AppCompanyIdWeaponsRoute,
  AppCompanyIdIndexRoute: AppCompanyIdIndexRoute,
}

const AppCompanyIdRouteWithChildren = AppCompanyIdRoute._addFileChildren(
  AppCompanyIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SuspendedRoute: SuspendedRoute,
  AppCompanyIdRoute: AppCompanyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
